import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
=======
import { Geist, Geist_Mono, Roboto } from "next/font/google";
>>>>>>> 6c67ec44efea7df2977059720b5f6cbdb680a107
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

<<<<<<< HEAD
=======
const roboto = Roboto({
  variable: "--font-geist-roboto",
  subsets: ['latin'],
});

>>>>>>> 6c67ec44efea7df2977059720b5f6cbdb680a107
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
<<<<<<< HEAD
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
=======
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased px-20`}
>>>>>>> 6c67ec44efea7df2977059720b5f6cbdb680a107
      >
        {children}
      </body>
    </html>
  );
}
